FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000 4000 5000

ENV NODE_ENV=production
RUN npm ci --only=production

USER root

CMD ["node", "server.js"]

# # Étape 1 : image de base légère
# FROM node:18-alpine

# # Étape 2 : répertoire de travail
# WORKDIR /app

# # Étape 3 : copier les fichiers nécessaires pour installer les dépendances
# COPY package*.json ./

# # Étape 4 : installer uniquement les dépendances de production
# RUN npm ci --only=production

# # Étape 5 : copier le reste du code
# COPY . .

# # Étape 6 : exposer le port
# EXPOSE 3000

# # Étape 7 : commande de démarrage
# CMD ["node", "server.js"]