FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN adduser -S nodejs
RUN chown -R nodejs /app

USER nodejs
EXPOSE 3000 4000 5000

ENV NODE_ENV=production
RUN npm ci --only=production

CMD ["node", "server.js"]